language: rust
sudo: required

before_script:
  - redis-server tests/fixtures/redis.conf

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: g+TEVQHwAa5Oksq1d32V9pgymv1fdOuns5c89m2gSRgjm6Z/eQmczIeo7jrKWdIkWY+HMiKJIp8+mFzE/Cl5FDX0SzxDZ39ru45Ujd1oIi91i3ikzv8Lh2sa9N3bbIwoVkYYA76+g1/yw3ZlmK5MbqkNpTjXDjbD8C06o7jDLXDFPhkZIkItrR1LeQrtmN022LWmKlQ+rrWnBkvVfteC1MbcZZwkpKWVSuUqB40Y9CevNjiHM/S21TgqiVV2l67REqowG0qTbBxYNSG9mLXxAiJhKkO3/Vy4N1MtAoiybA4WtiRCV7h8qCdWlabIqJXw7W9Je0NX3q9fzYUEs3Pa9IOLNKTJP3yQ01trRGDly3JCQr52HvHZEZ6CWjN4UJHLFuLOD/CVDCOstGmaLTlvgw8Fu2Zyb8BeAmTDjL30v7VLdztW3toVzi9wZtQg4tMfJoW2i/ZeOdlr9LuNuDzBOnEQLsrrvcQi00z8Ty7GQWPLTucGrc3wEctkjtClgEuVG3xvMGRh1CxGmXA2pItNXZr3gmFkiG9tDIUTyBGlG4+O2oQckiiu1jVBdPFRxCHXSDIV+cR3GzUL/kP5rnjebTa3+giAByxunOdtR6pMGKQs+c0qhm8k9wyN9QfzqWp+NFvxsyDMA02pCCLfvgj6v4op6eW4gEjaGgKSpHqRw1E=

notifications:
  email: false
